---
- name: FTP server is installed
  hosts: ftpservers
  vars_files:
    - vars/defaults-template.yml
    - vars/vars.yml
  tasks:
    - name: Packages are installed
      ansible.builtin.yum:
        name: "{{ vsftpd_package }}"
        state: present
    - name: Ensure service is started
      service:
        name: "{{ vsftpd_service }}"
        state: started
        enabled: true
    - name: Configuration file is installed
      ansible.builtin.template:
        src: template/vsftpd.conf.j2
        dest: "{{ vsftpd_config_file }}"
        owner: root
        group: root
        mode: 0600
        setype: etc_t
      notify: restart vsftpd
    - name: firewalld is installed
      ansible.builtin.dnf:
        name: firewalld
        state: present
    - name: firewalld is enabled
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true
    - name: firewalld to allow ftp service
      ansible.builtin.firewalld:
        service: ftp
         permanent: yes
        immediate: yes
        state: enabled 
    - name: firewall to allow ftp data port
      ansible.builtin.firewalld:
        port: 21000-21020/tcp
        permanent: yes
        immediate: yes
        state: enabled
  handlers:
    - name: restart vsftpd
      service:
        name: "{{ vsftpd_service }}"
        state: restarted