---
- name: set hostname
  hosts: all
  tasks:
  - name: use inventory to set hostname
    ansible.builtin.hostname:
      name: "{{ inventory_hostname }}"
      notify: restart
  restart:
    - name: reboot
      ansible.builtin.reboot:dd
  




  
  