---
- name: apache web server and install firewall
  hosts: ansible1.example.com
  tasks:
  - name: install apache web server
    debug:
      msg: install latest version of httpd and firewalld. use dnf module

  - name: copy content to /var/www/html/
    debug:
      msg: copy custom content hello this is a custom message. use copy module.

  - name:  firewalld and httpd are enable and running
    debug:
      msg: enable and running. use service module

  - name: firewalld to allow http service
    debug:
      msg: firewall is enabled immediately permanently. use firewall module
- name: test intranet web server
  hosts: localhost
  tasks:
  - name: Check that a page returns successfully
    debug:
      msg: Check that a page returns successfully. use uri module
  - name: print webpage content
    debug:
      msg: use debug to print webpage content
