---
- name: Create index.html from a template and save it as /ibmdata/htdocs/index.html owned by apache:apache
  ansible.builtin.template:
    src: index.html.j2
    dest: /ibmdata/htdocs/index.html
    owner: apache
    group: apache
    mode: '0644'
    backup: true
  become: true





 
